version: '2'
services:
  postgres:
    build:
      context: ./
      args:
        - buildno=1
      dockerfile: Dockerfile.database
    volumes:
      - $HOME/driver_django/postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=driver
      - POSTGRES_PASS=driver
      - POSTGRES_DBNAME=driver
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: database
    image:
      driver-database
  
  redis-server:
    image: redis
    container_name: redis-server
  
  windshaft:
    command: server.js
    container_name: windshaft
    links:
      - redis-server:redis
    depends_on:
      - redis-server
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ${WINDSHAFT_FILES}/windshaft/driver.js:/opt/windshaft/driver.js
      - ${WINDSHAFT_FILES}/windshaft/healthCheck.js:/opt/windshaft/healthCheck.js
      - ${WINDSHAFT_FILES}/windshaft/alphamarker.png:/opt/windshaft/alphamarker.png
      - ${WINDSHAFT_FILES}/windshaft/server.js:/opt/windshaft/server.js
    environment:
      - DRIVER_DB_NAME=driver
      - DRIVER_DB_USER=driver
      - DRIVER_DB_PASSWORD=${DATABASE_PASSWORD}
      - WINDSHAFT_DB_USER=driver
      - WINDSHAFT_DB_PASSWORD=${DATABASE_PASSWORD}
      - DRIVER_DB_HOST=database
      - DRIVER_DB_PORT=5432
      - DRIVER_APP_HOST=${PROTOCOL}://${HOST_NAME}
      - DRIVER_REDIS_HOST=redis-server
      - DRIVER_REDIS_PORT=6379
    image: quay.io/azavea/windshaft:0.1.0

