version: '3'
services:
  redis-server:
    name: "redis"
    image: redis
    dns-name-label: "redis-server-vidasegura"
    ports: 6379
    protocol: TCP
    command: "redis-server"
  
  driver-django:
    name: "django-vidasegura"
    dns-name-label: "driver-django-vidasegura"

    image: alien9/vidasegura
    dns-name-label: "driver-django-vidasegura"
    ports: 4000
    protocol: "TCP"
    command: "gunicorn driver.wsgi -w3 -b:4000 -kgevent --timeout 4000"
    volumes:
      - /opt/vidasegura/static:/var/www/static
      - /opt/vidasegura/mapserver:/opt/app/mapserver
    
    
    depends_on:
      - redis-server
      - mapserver
    environment:
      - HOST_URL=https://vidasegura.cetsp.com.br
      - HOSTNAME=vidasegura.cetsp.com.br
      - TIMEZONE=America/Sao_Paulo
      - DJANGO_ENV=production
      - DRIVER_DB_HOST=${DATABASE_HOST}
      - DRIVER_DB_NAME=${DATABASE_NAME}
      - DRIVER_DB_USER=${DATABASE_USERNAME}
      - DRIVER_DB_PASSWORD=${DATABASE_PASSWORD}
      - DRIVER_REDIS_HOST=redis-server-vidasegura
      - STATIC_ROOT=/var/www/static/
      - STATIC_URL=/static/ 
      - CONTAINER_NAME=vidasegura
      - MAPSERVER=mapserver-vidasegura
    name: driver-django-vidasegura
    name: django-vidasegura
    image: alien9/driver-django
      
  driver-celery:
    volumes:
      - /opt/vidasegura/zip:/var/www/media
    depends_on:
      - redis-server
    environment:
      - HOST_URL=https://vidasegura.cetsp.com.br
      - HOSTNAME=vidasegura.cetsp.com.br
      - COUNTRY_CODE=br
      - TIMEZONE=America/Sao_Paulo
      - DJANGO_ENV=production
      - DRIVER_DB_HOST=${DATABASE_HOST}
      - DRIVER_DB_NAME=${DATABASE_NAME}
      - DRIVER_DB_USER=${DATABASE_USERNAME}
      - DRIVER_DB_PASSWORD=${DATABASE_PASSWORD}
      - DRIVER_REDIS_HOST=redis-server-vidasegura
      - STATIC_ROOT=/var/www/static/
      - STATIC_URL=/static/ 
    command: "celery -A driver worker --queue=taskworker --loglevel=info --concurrency=4"
    name: driver-celery-vidasegura
    image: alien9/driver-django

          
  mapserver:
    name: mapserver-vidasegura
    dns-name-label:  mapserver-vidasegura
    volumes:
      - /opt/vidasegura/mapserver/:/etc/mapserver
    image: geodata/mapserver

