FROM postgres:9.5

ENV TZ America/La_Paz
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  postgis-2.5 postgresql-9.5-postgis-2.5-scripts
# set time zone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# add init script
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
COPY ./calculate_critical_spots.sql /docker-entrypoint-initdb.d/spots.sql


