from postgis/postgis

# add init script
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
COPY ./find_segments.sql /docker-entrypoint-initdb.d/spots.sql


