/usr/bin/docker run \
  --name windshaft \
  --publish 5000:5000 \
  --volume /opt/windshaft/driver.js:/opt/windshaft/driver.js \
  --volume /opt/windshaft/healthCheck.js:/opt/windshaft/healthCheck.js \
  --volume /opt/windshaft/alphamarker.png:/opt/windshaft/alphamarker.png \
  --volume /opt/windshaft/server.js:/opt/windshaft/server.js \
  --env DRIVER_DB_NAME='driver' \
  --env DRIVER_DB_USER='driver' \
  --env DRIVER_DB_PASSWORD='driver' \
  --env WINDSHAFT_DB_USER='driver' \
  --env WINDSHAFT_DB_PASSWORD='driver' \
  --env DRIVER_DB_HOST='172.17.0.1' \
  --env DRIVER_DB_PORT='5432' \
  --env DRIVER_APP_HOST='http://localhost:8000' \
  --env DRIVER_REDIS_HOST='172.17.0.1' \
  --env DRIVER_REDIS_PORT='6379' \
  --log-driver syslog \
  quay.io/azavea/windshaft:0.1.0 server.js