# Generated by Django 3.0.8 on 2020-11-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverTemRecord',
        ),
    ]
