# Generated by Django 3.2.4 on 2021-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrecord',
            name='mapillary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
