# Generated by Django 3.2.4 on 2022-03-29 12:43

from django.db import migrations, models
import django.db.models.deletion
from data.models import MapillaryData, DriverRecord
def fix_mapillary(apps, schema_editor):
    DriverRecord=apps.get_model('data', 'DriverRecord')
    MapillaryData=apps.get_model('data', 'MapillaryData')
    mr=DriverRecord.objects.filter(mapillary__isnull=False)
    for m in mr:
        md=MapillaryData(record=m,data=m.mapillary)
        md.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_driverrecord_mapillary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapillaryData',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.driverrecord')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(fix_mapillary),
    ]
