# Generated by Django 3.0.8 on 2020-12-09 17:39

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201120_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.TextField(max_length=8)),
                ('name', models.TextField(max_length=100)),
                ('content', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
            },
        ),
    ]
