# Generated by Django 3.2.4 on 2022-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_driverrecord_mapillary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrecord',
            name='segment',
            field=models.ManyToManyField(blank=True, to='data.RecordSegment'),
        ),
    ]
