# Generated by Django 3.2.4 on 2024-07-18 00:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_driverrecord_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='about',
            field=djrichtextfield.models.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
