# Generated by Django 3.2.4 on 2024-07-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_dictionary_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='about',
        ),
    ]
