# Generated by Django 3.2.4 on 2021-08-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0012_auto_20210826_1111'),
        ('data', '0007_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsegment',
            name='roadmap',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='black_spots.roadmap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordsegment',
            name='size',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='driverrecord',
            name='segment',
        ),
        migrations.AddField(
            model_name='driverrecord',
            name='segment',
            field=models.ManyToManyField(to='data.RecordSegment'),
        ),
    ]
