# Generated by Django 3.2.4 on 2024-07-18 00:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_dictionary_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='about',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
