# Generated by Django 3.2.4 on 2021-08-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0012_auto_20210826_1111'),
        ('data', '0008_auto_20210826_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsegment',
            name='roadmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='black_spots.roadmap'),
        ),
    ]
