# Generated by Django 3.2.4 on 2021-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_recordsegment_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrecord',
            name='mapillary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
