# Generated by Django 3.2.4 on 2024-12-06 19:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_dictionary_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='header',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
