# Generated by Django 3.2.4 on 2021-11-30 00:07

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20211020_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='content',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
