# Generated by Django 3.2.4 on 2024-12-06 20:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_dictionary_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='footer',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Footer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='header',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Header'),
        ),
    ]
