# Generated by Django 3.2.4 on 2025-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20241212_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='ordered_keys',
            field=models.JSONField(default=dict),
        ),
    ]
