# Generated by Django 3.2.4 on 2025-01-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_dictionary_ordered_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='ordered_keys',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
