# Generated by Django 3.0.8 on 2020-07-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20181003_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedupejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='recordauditlogentry',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=6),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='duplicate_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_record', to='data.DriverRecord'),
        ),
        migrations.AlterField(
            model_name='recordduplicate',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='data.DriverRecord'),
        ),
    ]
