# Generated by Django 3.2.4 on 2025-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20250204_0608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
