# Generated by Django 3.2.4 on 2025-02-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_delete_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='logo',
            field=models.TextField(blank=True, null=True, verbose_name='Logo'),
        ),
    ]
