# Generated by Django 3.2.4 on 2022-04-27 22:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
