# Generated by Django 3.2.4 on 2022-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_filters', '0002_alter_savedfilter_filter_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_json',
            field=models.JSONField(),
        ),
    ]
