# Generated by Django 3.2.4 on 2024-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'ordering': ('order',), 'verbose_name': 'Boundary', 'verbose_name_plural': 'Boundaries'},
        ),
        migrations.AddField(
            model_name='boundary',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
