# Generated by Django 3.2.4 on 2024-06-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0002_auto_20240605_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='plural_label',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
