# Generated by Django 3.2.4 on 2025-02-05 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0004_alter_recordschema_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='label',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
