# Generated by Django 3.2.4 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0005_alter_boundary_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='timezone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
