# Generated by Django 3.0.8 on 2020-10-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0025_auto_20180730_2038'),
    ]

    operations = [

    ]
