# Generated by Django 3.0.8 on 2020-08-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0025_auto_20180730_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name_plural': 'Boundaries'},
        ),
    ]
