# Generated by Django 3.0.8 on 2020-10-12 02:19

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0026_auto_20201012_1017'),
    ]

    operations = [
        
    ]
