# Generated by Django 3.0.8 on 2020-10-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0027_auto_20201012_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name_plural': 'Boundaries'},
        ),
    ]
