# Generated by Django 3.0.8 on 2020-11-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0028_auto_20201012_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name': 'Boundary', 'verbose_name_plural': 'Boundaries'},
        ),
        migrations.AlterModelOptions(
            name='boundarypolygon',
            options={'verbose_name': 'Boundary Polygon', 'verbose_name_plural': 'Boundary Polygons'},
        ),
    ]
