# Generated by Django 3.0.8 on 2020-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0007_auto_20160525_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackspotrecordsfile',
            name='csv',
            field=models.FileField(upload_to='blackspot_records/'),
        ),
        migrations.AlterField(
            model_name='blackspottrainingcsv',
            name='csv',
            field=models.FileField(upload_to='training/blackspot/'),
        ),
        migrations.AlterField(
            model_name='loadforecasttrainingcsv',
            name='csv',
            field=models.FileField(upload_to='training/forecast'),
        ),
        migrations.AlterField(
            model_name='roadsegmentsshapefile',
            name='shp_tgz',
            field=models.FileField(upload_to='road_segments/'),
        ),
    ]
