# Generated by Django 3.0.8 on 2020-10-12 02:26

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0008_auto_20200712_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('COMPLETE', 'Complete')], default='PENDING', max_length=10)),
                ('label', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('color', models.CharField(default='blue', max_length=64)),
                ('display_field', models.CharField(blank=True, max_length=10, null=True)),
                ('data_fields', django.db.models.JSONField(blank=True, null=True)),
                ('errors', django.db.models.JSONField(blank=True, null=True)),
                ('source_file', models.FileField(upload_to='boundaries/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.db.models.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('roadmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='black_spots.RoadMap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
