# Generated by Django 3.0.8 on 2020-11-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0009_road_roadmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'verbose_name': 'Road Map', 'verbose_name_plural': 'Road Maps'},
        ),
    ]
