# Generated by Django 3.0.8 on 2020-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0010_auto_20201120_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
