# Generated by Django 3.2.4 on 2021-08-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0011_road_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackspotset',
            name='roadmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='black_spots.roadmap'),
        ),
        migrations.AddField(
            model_name='blackspotset',
            name='title',
            field=models.TextField(default='Sin Titulo', max_length=100),
            preserve_default=False,
        ),
    ]
