# Generated by Django 3.2.4 on 2021-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0012_auto_20210826_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackspotset',
            name='size',
            field=models.IntegerField(default=100),
        ),
    ]
