# Generated by Django 3.2.4 on 2021-08-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0013_blackspotset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackspot',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blackspot',
            name='black_spot_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='black_spots.blackspotset'),
        ),
    ]
