# Generated by Django 3.2.4 on 2021-10-12 22:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_spots', '0015_blackspotset_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackspotset',
            options={'verbose_name': 'Critical Spots', 'verbose_name_plural': 'Critical Spots'},
        ),
        migrations.AddField(
            model_name='blackspot',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
